module.exports = {
  components: [
    'virtual',
    'keyboard',
    'mousewheel',
    'navigation',
    'pagination',
    'scrollbar',
    'parallax',
    'zoom',
    'lazy',
    'controller',
    'a11y',
    'history',
    'hash-navigation',
    'autoplay',
    'effect-fade',
    'effect-cube',
    'effect-flip',
    'effect-coverflow',
    'thumbs',
  ],
  target: 'universal',
  themeColor: '#9dff00',
  colors: {
    white: '#ffffff',
    black: '#000000',
  },
};
